travis:
  secure:
    BINSTAR_TOKEN: YK/cHMtdTW3z006w7MmpiIJTpS7bZqcAuXY3SulIh4LwmfgcnB2PSJ2X8D3F9B6pnp3sJPIJ2Bt2XmbdOzdEmMyskVtB06jUeQWTgvrQhSGxURsPqr69YgBBtYmeQvd5/clkTgtV58nlUntXvNbe/CiXhJtLLX8fV22fTb6ihue241OkRXe4x4Lzb91kby+KCsJozmYFpYpymiDqbAlm7vznGIZDfQ1cgfT2MMRbyTuOPB6ClS7uhqS6txE0qGQBCinfv3O4j3rrro5eP+6D/Idq8sf9b9/ogZ7sdpGrUOxd+96oFo+isjHFp2cQYs3F3Yma74WAQdT1PtPMtIzGu2+RGp2btA+u4FbaEgr0xJ9jcw4mp9dafLsoA4jnHaeB6SF4dV+YDCHmY91YBo5oN2AhQrZ15kneoQTV0U4nXn28jQLnfExeABf3/9UnBWnry33jixV38OMSYfreLBq3sVRB6zTYGYH6nu58+5mpmTHunavXCM6DxPFTQZsoiKxoYrEnsjH795VpiYOHbjDet0s0hojwTY/2+lvkJf2L/aFK9Ga8VKDQiiQmU0czdkYAxcz5hzVGol95RI/SDV0g0Jw/JlD6VrmfejynzZHV4P93IhI0rE2tdJ0SLb6O2Wd8LCR6NT6VXAwpbvnhcnJpdFjg+jb6xgk+qn74HsQHBAQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
